services:
  - type: web
    name: task-flow-backend
    runtime: node
    buildCommand: npm install --legacy-peer-deps && npx prisma generate && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: DATABASE_URL
        value: ${DATABASE_URL}
      - key: JWT_SECRET
        value: ${JWT_SECRET}
      - key: FRONTEND_URL
        value: https://task-flow-frontend-0t16.onrender.com
      - key: SMTP_HOST
        value: smtp.resend.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        value: resend
      - key: SMTP_FROM
        value: onboarding@resend.dev
      - key: SMTP_FROM_NAME
        value: TaskPilot
